---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: terraform-state-storage
  namespace: flux-system
spec:
  path: ./kubernetes/apps/infrastructure/terraform/state-storage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: immich-kubernetes
  dependsOn: database-cloudnative-pg
  interval: 30m
  retryInterval: 1m
  timeout: 3m
