apiVersion: v1
kind: Service
metadata:
  name: tf-state-storage-nodeport
  namespace: terraform
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: tf-state-storage
    role: primary
  ports:
    - port: 5432
      nodePort: 30635